server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Убираем /index.html из конца, чтобы Nginx искал реальные .html файлы
        try_files $uri $uri.html $uri/ =404;
    }

    # Прокси для API (аналог того, что было в vite.config.js)
    location /api/ {
        # Перенаправляем на целевой сервер
        proxy_pass https://app.epsti.site/;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host app.epsti.site;
        proxy_cache_bypass $http_upgrade;

        # Важно: если на целевом сервере нет пути /api/,
        # Nginx с "proxy_pass" и слешем в конце сам обрежет /api/
    }
}